[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "seoul_bike_sharing_demand"
version = "0.0.1"
description = "MLOps applied to Seoul Bike sharing demand"
authors = [
  { name = "Equipo_48" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.13.0"


[tool.ruff]
line-length = 99
src = ["seoul_bike_sharing_demand"]
include = ["pyproject.toml", "seoul_bike_sharing_demand/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["seoul_bike_sharing_demand"]
force-sort-within-sections = true

